# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\Tao Chiang\Desktop\install"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\Tao Chiang\Desktop\install"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Tao Chiang\Desktop\install\CMakeFiles" "C:\Users\Tao Chiang\Desktop\install\CMakeFiles\progress.marks"
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Tao Chiang\Desktop\install\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Launcher

# Build rule for target.
launcher: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 launcher
.PHONY : launcher

# fast build rule for target.
launcher/fast:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/build
.PHONY : launcher/fast

#=============================================================================
# Target rules for targets named sound_debug

# Build rule for target.
sound_debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sound_debug
.PHONY : sound_debug

# fast build rule for target.
sound_debug/fast:
	$(MAKE) -f CMakeFiles\sound_debug.dir\build.make CMakeFiles/sound_debug.dir/build
.PHONY : sound_debug/fast

#=============================================================================
# Target rules for targets named leaderboard

# Build rule for target.
leaderboard: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 leaderboard
.PHONY : leaderboard

# fast build rule for target.
leaderboard/fast:
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/build
.PHONY : leaderboard/fast

#=============================================================================
# Target rules for targets named file_debug

# Build rule for target.
file_debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 file_debug
.PHONY : file_debug

# fast build rule for target.
file_debug/fast:
	$(MAKE) -f CMakeFiles\file_debug.dir\build.make CMakeFiles/file_debug.dir/build
.PHONY : file_debug/fast

#=============================================================================
# Target rules for targets named single_main

# Build rule for target.
single_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 single_main
.PHONY : single_main

# fast build rule for target.
single_main/fast:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/build
.PHONY : single_main/fast

File_System/debug/file_debug.obj: File_System/debug/file_debug.c.obj

.PHONY : File_System/debug/file_debug.obj

# target to build an object file
File_System/debug/file_debug.c.obj:
	$(MAKE) -f CMakeFiles\file_debug.dir\build.make CMakeFiles/file_debug.dir/File_System/debug/file_debug.c.obj
.PHONY : File_System/debug/file_debug.c.obj

File_System/debug/file_debug.i: File_System/debug/file_debug.c.i

.PHONY : File_System/debug/file_debug.i

# target to preprocess a source file
File_System/debug/file_debug.c.i:
	$(MAKE) -f CMakeFiles\file_debug.dir\build.make CMakeFiles/file_debug.dir/File_System/debug/file_debug.c.i
.PHONY : File_System/debug/file_debug.c.i

File_System/debug/file_debug.s: File_System/debug/file_debug.c.s

.PHONY : File_System/debug/file_debug.s

# target to generate assembly for a file
File_System/debug/file_debug.c.s:
	$(MAKE) -f CMakeFiles\file_debug.dir\build.make CMakeFiles/file_debug.dir/File_System/debug/file_debug.c.s
.PHONY : File_System/debug/file_debug.c.s

File_System/file_system_game_status.obj: File_System/file_system_game_status.c.obj

.PHONY : File_System/file_system_game_status.obj

# target to build an object file
File_System/file_system_game_status.c.obj:
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/File_System/file_system_game_status.c.obj
	$(MAKE) -f CMakeFiles\file_debug.dir\build.make CMakeFiles/file_debug.dir/File_System/file_system_game_status.c.obj
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/File_System/file_system_game_status.c.obj
.PHONY : File_System/file_system_game_status.c.obj

File_System/file_system_game_status.i: File_System/file_system_game_status.c.i

.PHONY : File_System/file_system_game_status.i

# target to preprocess a source file
File_System/file_system_game_status.c.i:
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/File_System/file_system_game_status.c.i
	$(MAKE) -f CMakeFiles\file_debug.dir\build.make CMakeFiles/file_debug.dir/File_System/file_system_game_status.c.i
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/File_System/file_system_game_status.c.i
.PHONY : File_System/file_system_game_status.c.i

File_System/file_system_game_status.s: File_System/file_system_game_status.c.s

.PHONY : File_System/file_system_game_status.s

# target to generate assembly for a file
File_System/file_system_game_status.c.s:
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/File_System/file_system_game_status.c.s
	$(MAKE) -f CMakeFiles\file_debug.dir\build.make CMakeFiles/file_debug.dir/File_System/file_system_game_status.c.s
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/File_System/file_system_game_status.c.s
.PHONY : File_System/file_system_game_status.c.s

File_System/file_system_linked_list.obj: File_System/file_system_linked_list.c.obj

.PHONY : File_System/file_system_linked_list.obj

# target to build an object file
File_System/file_system_linked_list.c.obj:
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/File_System/file_system_linked_list.c.obj
	$(MAKE) -f CMakeFiles\file_debug.dir\build.make CMakeFiles/file_debug.dir/File_System/file_system_linked_list.c.obj
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/File_System/file_system_linked_list.c.obj
.PHONY : File_System/file_system_linked_list.c.obj

File_System/file_system_linked_list.i: File_System/file_system_linked_list.c.i

.PHONY : File_System/file_system_linked_list.i

# target to preprocess a source file
File_System/file_system_linked_list.c.i:
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/File_System/file_system_linked_list.c.i
	$(MAKE) -f CMakeFiles\file_debug.dir\build.make CMakeFiles/file_debug.dir/File_System/file_system_linked_list.c.i
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/File_System/file_system_linked_list.c.i
.PHONY : File_System/file_system_linked_list.c.i

File_System/file_system_linked_list.s: File_System/file_system_linked_list.c.s

.PHONY : File_System/file_system_linked_list.s

# target to generate assembly for a file
File_System/file_system_linked_list.c.s:
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/File_System/file_system_linked_list.c.s
	$(MAKE) -f CMakeFiles\file_debug.dir\build.make CMakeFiles/file_debug.dir/File_System/file_system_linked_list.c.s
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/File_System/file_system_linked_list.c.s
.PHONY : File_System/file_system_linked_list.c.s

Leader_Board/leaderboard_main.obj: Leader_Board/leaderboard_main.c.obj

.PHONY : Leader_Board/leaderboard_main.obj

# target to build an object file
Leader_Board/leaderboard_main.c.obj:
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/Leader_Board/leaderboard_main.c.obj
.PHONY : Leader_Board/leaderboard_main.c.obj

Leader_Board/leaderboard_main.i: Leader_Board/leaderboard_main.c.i

.PHONY : Leader_Board/leaderboard_main.i

# target to preprocess a source file
Leader_Board/leaderboard_main.c.i:
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/Leader_Board/leaderboard_main.c.i
.PHONY : Leader_Board/leaderboard_main.c.i

Leader_Board/leaderboard_main.s: Leader_Board/leaderboard_main.c.s

.PHONY : Leader_Board/leaderboard_main.s

# target to generate assembly for a file
Leader_Board/leaderboard_main.c.s:
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/Leader_Board/leaderboard_main.c.s
.PHONY : Leader_Board/leaderboard_main.c.s

Sound/debug/sound_debug.obj: Sound/debug/sound_debug.c.obj

.PHONY : Sound/debug/sound_debug.obj

# target to build an object file
Sound/debug/sound_debug.c.obj:
	$(MAKE) -f CMakeFiles\sound_debug.dir\build.make CMakeFiles/sound_debug.dir/Sound/debug/sound_debug.c.obj
.PHONY : Sound/debug/sound_debug.c.obj

Sound/debug/sound_debug.i: Sound/debug/sound_debug.c.i

.PHONY : Sound/debug/sound_debug.i

# target to preprocess a source file
Sound/debug/sound_debug.c.i:
	$(MAKE) -f CMakeFiles\sound_debug.dir\build.make CMakeFiles/sound_debug.dir/Sound/debug/sound_debug.c.i
.PHONY : Sound/debug/sound_debug.c.i

Sound/debug/sound_debug.s: Sound/debug/sound_debug.c.s

.PHONY : Sound/debug/sound_debug.s

# target to generate assembly for a file
Sound/debug/sound_debug.c.s:
	$(MAKE) -f CMakeFiles\sound_debug.dir\build.make CMakeFiles/sound_debug.dir/Sound/debug/sound_debug.c.s
.PHONY : Sound/debug/sound_debug.c.s

Sound/sound.obj: Sound/sound.c.obj

.PHONY : Sound/sound.obj

# target to build an object file
Sound/sound.c.obj:
	$(MAKE) -f CMakeFiles\sound_debug.dir\build.make CMakeFiles/sound_debug.dir/Sound/sound.c.obj
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/Sound/sound.c.obj
.PHONY : Sound/sound.c.obj

Sound/sound.i: Sound/sound.c.i

.PHONY : Sound/sound.i

# target to preprocess a source file
Sound/sound.c.i:
	$(MAKE) -f CMakeFiles\sound_debug.dir\build.make CMakeFiles/sound_debug.dir/Sound/sound.c.i
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/Sound/sound.c.i
.PHONY : Sound/sound.c.i

Sound/sound.s: Sound/sound.c.s

.PHONY : Sound/sound.s

# target to generate assembly for a file
Sound/sound.c.s:
	$(MAKE) -f CMakeFiles\sound_debug.dir\build.make CMakeFiles/sound_debug.dir/Sound/sound.c.s
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/Sound/sound.c.s
.PHONY : Sound/sound.c.s

launcher/launcher_main.obj: launcher/launcher_main.c.obj

.PHONY : launcher/launcher_main.obj

# target to build an object file
launcher/launcher_main.c.obj:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/launcher/launcher_main.c.obj
.PHONY : launcher/launcher_main.c.obj

launcher/launcher_main.i: launcher/launcher_main.c.i

.PHONY : launcher/launcher_main.i

# target to preprocess a source file
launcher/launcher_main.c.i:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/launcher/launcher_main.c.i
.PHONY : launcher/launcher_main.c.i

launcher/launcher_main.s: launcher/launcher_main.c.s

.PHONY : launcher/launcher_main.s

# target to generate assembly for a file
launcher/launcher_main.c.s:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/launcher/launcher_main.c.s
.PHONY : launcher/launcher_main.c.s

libgraphics/exceptio.obj: libgraphics/exceptio.c.obj

.PHONY : libgraphics/exceptio.obj

# target to build an object file
libgraphics/exceptio.c.obj:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/exceptio.c.obj
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/exceptio.c.obj
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/exceptio.c.obj
.PHONY : libgraphics/exceptio.c.obj

libgraphics/exceptio.i: libgraphics/exceptio.c.i

.PHONY : libgraphics/exceptio.i

# target to preprocess a source file
libgraphics/exceptio.c.i:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/exceptio.c.i
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/exceptio.c.i
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/exceptio.c.i
.PHONY : libgraphics/exceptio.c.i

libgraphics/exceptio.s: libgraphics/exceptio.c.s

.PHONY : libgraphics/exceptio.s

# target to generate assembly for a file
libgraphics/exceptio.c.s:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/exceptio.c.s
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/exceptio.c.s
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/exceptio.c.s
.PHONY : libgraphics/exceptio.c.s

libgraphics/genlib.obj: libgraphics/genlib.c.obj

.PHONY : libgraphics/genlib.obj

# target to build an object file
libgraphics/genlib.c.obj:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/genlib.c.obj
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/genlib.c.obj
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/genlib.c.obj
.PHONY : libgraphics/genlib.c.obj

libgraphics/genlib.i: libgraphics/genlib.c.i

.PHONY : libgraphics/genlib.i

# target to preprocess a source file
libgraphics/genlib.c.i:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/genlib.c.i
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/genlib.c.i
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/genlib.c.i
.PHONY : libgraphics/genlib.c.i

libgraphics/genlib.s: libgraphics/genlib.c.s

.PHONY : libgraphics/genlib.s

# target to generate assembly for a file
libgraphics/genlib.c.s:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/genlib.c.s
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/genlib.c.s
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/genlib.c.s
.PHONY : libgraphics/genlib.c.s

libgraphics/graphics.obj: libgraphics/graphics.c.obj

.PHONY : libgraphics/graphics.obj

# target to build an object file
libgraphics/graphics.c.obj:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/graphics.c.obj
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/graphics.c.obj
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/graphics.c.obj
.PHONY : libgraphics/graphics.c.obj

libgraphics/graphics.i: libgraphics/graphics.c.i

.PHONY : libgraphics/graphics.i

# target to preprocess a source file
libgraphics/graphics.c.i:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/graphics.c.i
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/graphics.c.i
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/graphics.c.i
.PHONY : libgraphics/graphics.c.i

libgraphics/graphics.s: libgraphics/graphics.c.s

.PHONY : libgraphics/graphics.s

# target to generate assembly for a file
libgraphics/graphics.c.s:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/graphics.c.s
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/graphics.c.s
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/graphics.c.s
.PHONY : libgraphics/graphics.c.s

libgraphics/random.obj: libgraphics/random.c.obj

.PHONY : libgraphics/random.obj

# target to build an object file
libgraphics/random.c.obj:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/random.c.obj
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/random.c.obj
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/random.c.obj
.PHONY : libgraphics/random.c.obj

libgraphics/random.i: libgraphics/random.c.i

.PHONY : libgraphics/random.i

# target to preprocess a source file
libgraphics/random.c.i:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/random.c.i
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/random.c.i
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/random.c.i
.PHONY : libgraphics/random.c.i

libgraphics/random.s: libgraphics/random.c.s

.PHONY : libgraphics/random.s

# target to generate assembly for a file
libgraphics/random.c.s:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/random.c.s
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/random.c.s
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/random.c.s
.PHONY : libgraphics/random.c.s

libgraphics/simpio.obj: libgraphics/simpio.c.obj

.PHONY : libgraphics/simpio.obj

# target to build an object file
libgraphics/simpio.c.obj:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/simpio.c.obj
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/simpio.c.obj
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/simpio.c.obj
.PHONY : libgraphics/simpio.c.obj

libgraphics/simpio.i: libgraphics/simpio.c.i

.PHONY : libgraphics/simpio.i

# target to preprocess a source file
libgraphics/simpio.c.i:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/simpio.c.i
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/simpio.c.i
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/simpio.c.i
.PHONY : libgraphics/simpio.c.i

libgraphics/simpio.s: libgraphics/simpio.c.s

.PHONY : libgraphics/simpio.s

# target to generate assembly for a file
libgraphics/simpio.c.s:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/simpio.c.s
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/simpio.c.s
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/simpio.c.s
.PHONY : libgraphics/simpio.c.s

libgraphics/strlib.obj: libgraphics/strlib.c.obj

.PHONY : libgraphics/strlib.obj

# target to build an object file
libgraphics/strlib.c.obj:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/strlib.c.obj
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/strlib.c.obj
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/strlib.c.obj
.PHONY : libgraphics/strlib.c.obj

libgraphics/strlib.i: libgraphics/strlib.c.i

.PHONY : libgraphics/strlib.i

# target to preprocess a source file
libgraphics/strlib.c.i:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/strlib.c.i
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/strlib.c.i
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/strlib.c.i
.PHONY : libgraphics/strlib.c.i

libgraphics/strlib.s: libgraphics/strlib.c.s

.PHONY : libgraphics/strlib.s

# target to generate assembly for a file
libgraphics/strlib.c.s:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/libgraphics/strlib.c.s
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/libgraphics/strlib.c.s
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/libgraphics/strlib.c.s
.PHONY : libgraphics/strlib.c.s

simpleGUI/imgui.obj: simpleGUI/imgui.c.obj

.PHONY : simpleGUI/imgui.obj

# target to build an object file
simpleGUI/imgui.c.obj:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/simpleGUI/imgui.c.obj
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/simpleGUI/imgui.c.obj
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/simpleGUI/imgui.c.obj
.PHONY : simpleGUI/imgui.c.obj

simpleGUI/imgui.i: simpleGUI/imgui.c.i

.PHONY : simpleGUI/imgui.i

# target to preprocess a source file
simpleGUI/imgui.c.i:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/simpleGUI/imgui.c.i
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/simpleGUI/imgui.c.i
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/simpleGUI/imgui.c.i
.PHONY : simpleGUI/imgui.c.i

simpleGUI/imgui.s: simpleGUI/imgui.c.s

.PHONY : simpleGUI/imgui.s

# target to generate assembly for a file
simpleGUI/imgui.c.s:
	$(MAKE) -f CMakeFiles\launcher.dir\build.make CMakeFiles/launcher.dir/simpleGUI/imgui.c.s
	$(MAKE) -f CMakeFiles\leaderboard.dir\build.make CMakeFiles/leaderboard.dir/simpleGUI/imgui.c.s
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/simpleGUI/imgui.c.s
.PHONY : simpleGUI/imgui.c.s

single_src/controller/handlers.obj: single_src/controller/handlers.c.obj

.PHONY : single_src/controller/handlers.obj

# target to build an object file
single_src/controller/handlers.c.obj:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/controller/handlers.c.obj
.PHONY : single_src/controller/handlers.c.obj

single_src/controller/handlers.i: single_src/controller/handlers.c.i

.PHONY : single_src/controller/handlers.i

# target to preprocess a source file
single_src/controller/handlers.c.i:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/controller/handlers.c.i
.PHONY : single_src/controller/handlers.c.i

single_src/controller/handlers.s: single_src/controller/handlers.c.s

.PHONY : single_src/controller/handlers.s

# target to generate assembly for a file
single_src/controller/handlers.c.s:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/controller/handlers.c.s
.PHONY : single_src/controller/handlers.c.s

single_src/model/consts.obj: single_src/model/consts.c.obj

.PHONY : single_src/model/consts.obj

# target to build an object file
single_src/model/consts.c.obj:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/model/consts.c.obj
.PHONY : single_src/model/consts.c.obj

single_src/model/consts.i: single_src/model/consts.c.i

.PHONY : single_src/model/consts.i

# target to preprocess a source file
single_src/model/consts.c.i:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/model/consts.c.i
.PHONY : single_src/model/consts.c.i

single_src/model/consts.s: single_src/model/consts.c.s

.PHONY : single_src/model/consts.s

# target to generate assembly for a file
single_src/model/consts.c.s:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/model/consts.c.s
.PHONY : single_src/model/consts.c.s

single_src/model/model.obj: single_src/model/model.c.obj

.PHONY : single_src/model/model.obj

# target to build an object file
single_src/model/model.c.obj:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/model/model.c.obj
.PHONY : single_src/model/model.c.obj

single_src/model/model.i: single_src/model/model.c.i

.PHONY : single_src/model/model.i

# target to preprocess a source file
single_src/model/model.c.i:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/model/model.c.i
.PHONY : single_src/model/model.c.i

single_src/model/model.s: single_src/model/model.c.s

.PHONY : single_src/model/model.s

# target to generate assembly for a file
single_src/model/model.c.s:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/model/model.c.s
.PHONY : single_src/model/model.c.s

single_src/single_main.obj: single_src/single_main.c.obj

.PHONY : single_src/single_main.obj

# target to build an object file
single_src/single_main.c.obj:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/single_main.c.obj
.PHONY : single_src/single_main.c.obj

single_src/single_main.i: single_src/single_main.c.i

.PHONY : single_src/single_main.i

# target to preprocess a source file
single_src/single_main.c.i:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/single_main.c.i
.PHONY : single_src/single_main.c.i

single_src/single_main.s: single_src/single_main.c.s

.PHONY : single_src/single_main.s

# target to generate assembly for a file
single_src/single_main.c.s:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/single_main.c.s
.PHONY : single_src/single_main.c.s

single_src/view/drawers.obj: single_src/view/drawers.c.obj

.PHONY : single_src/view/drawers.obj

# target to build an object file
single_src/view/drawers.c.obj:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/view/drawers.c.obj
.PHONY : single_src/view/drawers.c.obj

single_src/view/drawers.i: single_src/view/drawers.c.i

.PHONY : single_src/view/drawers.i

# target to preprocess a source file
single_src/view/drawers.c.i:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/view/drawers.c.i
.PHONY : single_src/view/drawers.c.i

single_src/view/drawers.s: single_src/view/drawers.c.s

.PHONY : single_src/view/drawers.s

# target to generate assembly for a file
single_src/view/drawers.c.s:
	$(MAKE) -f CMakeFiles\single_main.dir\build.make CMakeFiles/single_main.dir/single_src/view/drawers.c.s
.PHONY : single_src/view/drawers.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... launcher
	@echo ... sound_debug
	@echo ... leaderboard
	@echo ... file_debug
	@echo ... single_main
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... File_System/debug/file_debug.obj
	@echo ... File_System/debug/file_debug.i
	@echo ... File_System/debug/file_debug.s
	@echo ... File_System/file_system_game_status.obj
	@echo ... File_System/file_system_game_status.i
	@echo ... File_System/file_system_game_status.s
	@echo ... File_System/file_system_linked_list.obj
	@echo ... File_System/file_system_linked_list.i
	@echo ... File_System/file_system_linked_list.s
	@echo ... Leader_Board/leaderboard_main.obj
	@echo ... Leader_Board/leaderboard_main.i
	@echo ... Leader_Board/leaderboard_main.s
	@echo ... Sound/debug/sound_debug.obj
	@echo ... Sound/debug/sound_debug.i
	@echo ... Sound/debug/sound_debug.s
	@echo ... Sound/sound.obj
	@echo ... Sound/sound.i
	@echo ... Sound/sound.s
	@echo ... launcher/launcher_main.obj
	@echo ... launcher/launcher_main.i
	@echo ... launcher/launcher_main.s
	@echo ... libgraphics/exceptio.obj
	@echo ... libgraphics/exceptio.i
	@echo ... libgraphics/exceptio.s
	@echo ... libgraphics/genlib.obj
	@echo ... libgraphics/genlib.i
	@echo ... libgraphics/genlib.s
	@echo ... libgraphics/graphics.obj
	@echo ... libgraphics/graphics.i
	@echo ... libgraphics/graphics.s
	@echo ... libgraphics/random.obj
	@echo ... libgraphics/random.i
	@echo ... libgraphics/random.s
	@echo ... libgraphics/simpio.obj
	@echo ... libgraphics/simpio.i
	@echo ... libgraphics/simpio.s
	@echo ... libgraphics/strlib.obj
	@echo ... libgraphics/strlib.i
	@echo ... libgraphics/strlib.s
	@echo ... simpleGUI/imgui.obj
	@echo ... simpleGUI/imgui.i
	@echo ... simpleGUI/imgui.s
	@echo ... single_src/controller/handlers.obj
	@echo ... single_src/controller/handlers.i
	@echo ... single_src/controller/handlers.s
	@echo ... single_src/model/consts.obj
	@echo ... single_src/model/consts.i
	@echo ... single_src/model/consts.s
	@echo ... single_src/model/model.obj
	@echo ... single_src/model/model.i
	@echo ... single_src/model/model.s
	@echo ... single_src/single_main.obj
	@echo ... single_src/single_main.i
	@echo ... single_src/single_main.s
	@echo ... single_src/view/drawers.obj
	@echo ... single_src/view/drawers.i
	@echo ... single_src/view/drawers.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

